//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidCaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confirmed_Cases
    {
        public int Id { get; set; }
        public int Hospital_Id { get; set; }
        public int Male_Confirmed_Cases { get; set; }
        public int Female_Confirmed_Cases { get; set; }
        public int Children_Confirmed_Cases { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Hospital_Details Hospital_Details { get; set; }
    }
}
