//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidCaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient_Details()
        {
            this.Confirmed_Cases = new HashSet<Confirmed_Cases>();
            this.Confirmed_Deaths = new HashSet<Confirmed_Deaths>();
            this.Confirmed_Recoveries = new HashSet<Confirmed_Recoveries>();
            this.Hospitalized_Details = new HashSet<Hospitalized_Details>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Address { get; set; }
        public int Test_Id { get; set; }
        public System.DateTime Joining_Date { get; set; }
        public Nullable<System.DateTime> Discharge_Date { get; set; }
        public string Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Confirmed_Cases> Confirmed_Cases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Confirmed_Deaths> Confirmed_Deaths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Confirmed_Recoveries> Confirmed_Recoveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalized_Details> Hospitalized_Details { get; set; }
        public virtual Tested_Individuals Tested_Individuals { get; set; }
    }
}
