//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidCaseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tested_Individuals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tested_Individuals()
        {
            this.Patient_Details = new HashSet<Patient_Details>();
        }
    
        public int Id { get; set; }
        public string Patient_Name { get; set; }
        public string Sample_Taken { get; set; }
        public string Test_Status { get; set; }
        public string Test_Results { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient_Details> Patient_Details { get; set; }
    }
}
